export const projectsData = [
  {
    id: 1,
    title: "Movie Swiper",
    subTitle: "Top Rated Movie Board",
    img: [
      "/images/movieswiper/1.png",
      "/images/movieswiper/2.png",
      "/images/movieswiper/3.png",
      "/images/movieswiper/4.png",
    ],
    link: "movie-swiper",
    url: "https://movie-swiper-r3f.vercel.app/",
    desc: "This interactive web application allows users to explore and select movies based on their preferences with a simple swipe gesture. ",
    role: "Design / Development",
    client: "-",
    date: "Aug, 2023",
    technologies: ["Three.js", "GSAP", "RESTful APIs"],
  },
  {
    id: 2,
    title: "Weather App",
    subTitle: "Weather Forecast Website",
    img: [
      "/images/weatherapp/1.png",
      "/images/weatherapp/2.png",
      "/images/weatherapp/3.png",
    ],
    link: "weather-app",
    url: "https://weather-app-2-wine.vercel.app/",
    desc: "Responsive Weather Dashboard Application based on Next.js. The application integrates third-party APIs from OpenWeather to dynamically retrieve and present weather data.",
    role: "Development",
    client: "-",
    date: "Sept, 2023",
    technologies: ["Next.js", "Framer motion", "GSAP"],
  },
  {
    id: 3,
    title: "Movie Website",
    subTitle: "Fullstack Website",
    img: [
      "/images/movieapp/login.png",
      "/images/movieapp/register.png",
      "/images/movieapp/home.png",
      "/images/movieapp/favorite.png",
      "/images/movieapp/comment.png",
      "/images/movieapp/details.png",
    ],
    link: "movie-web",
    url: "#",
    desc: "This movie application is a platform designed to enhance the movie-watching experience for users. Built on the MERN stack.",
    role: "Design / Development",
    client: "-",
    date: "Nov, 2024",
    technologies: ["React", "MongoDB", "Express.js"],
  },
  {
    id: 4,
    title: "Wander Social",
    subTitle: "Social App Official Website",
    img: [
      "/images/wander/wander1.png",
      "/images/wander/wander2.png",
      "/images/wander/wander3.png",
    ],
    link: "wander-social",
    url: "https://wander.one/",
    desc: "Develop a lightweight official website for an AI-powered social app, featuring cool animation effects to enhance user engagement.",
    role: "Development",
    client: "ActEarn Inc.",
    date: "Nov, 2024",
    technologies: ["Next.js", "Framer motion", "GSAP"],
  },
  {
    id: 5,
    title: "Portfolio 2023",
    subTitle: "WebGL",
    img: [
      "/images/portfolio/portfolio1.png",
      "/images/portfolio/portfolio2.png",
      "/images/portfolio/portfolio3.png",
      "/images/portfolio/portfolio4.png",
      "/images/portfolio/portfolio5.png",
    ],
    link: "portfolio2023",
    url: "https://synnies-journey.vercel.app/",
    desc: "Use Blender to design a unique planet, and leverage Three.js to create an immersive storytelling experience.",
    role: "Design / Development",
    client: "-",
    date: "Nov, 2023",
    technologies: ["Blender", "React", "Three.js", "GLSL"],
  },
  {
    id: 6,
    title: "Voxel Bunny",
    subTitle: "3D Shader",
    img: [
      "/images/bunny/bunny1.png",
      "/images/bunny/bunny2.png",
      "/images/bunny/bunny3.png",
    ],
    link: "voxel-bunny",
    url: "https://voxel-web-sigma.vercel.app/",
    desc: "Use GLSL shaders to create a voxel effect and apply post-processing techniques to achieve a blurry effect.",
    role: "Design / Development",
    client: "-",
    date: "Nov, 2024",
    technologies: ["Three.js", "GLSL"],
  },
  {
    id: 7,
    title: "3D Product Customization Platform",
    subTitle: "Interactive 3D Shader & Customization",
    img: [
      "/images/customization-web/1.png",
      "/images/customization-web/2.png",
      "/images/customization-web/3.png",
      "/images/customization-web/4.png",
      "/images/customization-web/5.png",
      "/images/customization-web/6.png",
    ],
    link: "customization-web",
    url: "https://github.com/synnielxy/3d-product-customization-platform",
    desc: "Built with Next.js 14 and TypeScript for efficient server-side rendering and dynamic frontend functionality, paired with Supabase (PostgreSQL) and Prisma ORM for reliable database management.",
    role: "Design / Development",
    client: "-",
    date: "Dec, 2024",
    technologies: [
      "Nextjs 14",
      "TypeScript",
      "Supabase",
      "Prisma ORM",
      "Stripe Subsctiptions",
      "Clerk Authentication",
      "Tailwind CSS",
      "Shadcn UI",
      "Three.js",
      "Blender",
    ],
  },
  {
    id: 8,
    title: "Pax Landing Page",
    subTitle: "Web Design / Development & Animation",
    img: ["/images/pax/1.png", 
      "/images/pax/2.png", 
      "/images/pax/3.png",
      "/images/pax/4.png",
      "/images/pax/5.png",
      "/images/pax/6.png",
      "/images/pax/7.png",
      "/images/pax/8.png",
      "/images/pax/9.png",
      "/images/pax/10.png",
    ],
    link: "pax",
    url: "https://paxai.com/",
    desc: "Developed a modern landing page for Pax using Next.js and TypeScript, delivering efficient server-side rendering and dynamic frontend functionality. Implemented custom animations using code to enhance user engagement and create a seamless interactive experience.",
    role: "Design / Development",
    client: "Pax",
    date: "Jan, 2025",
    technologies: [
      "Figma",
      "Nextjs 14",
      "TypeScript",
      "Tailwind CSS",
      "Shadcn UI",
      "SVG",
      "Framer Motion",
    ],
  },
];
